"""add_user_preference_fields

Revision ID: 4712b94ac0d8
Revises: 
Create Date: 2026-04-22 10:07:23.363550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4712b94ac0d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trip_day_trip_id', table_name='trip_day')
    op.drop_table('trip_day')
    op.drop_index('idx_checkin_created_at', table_name='checkin')
    op.drop_index('idx_checkin_user_id', table_name='checkin')
    op.drop_table('checkin')
    op.drop_index('idx_attractions_category', table_name='attractions')
    op.drop_index('idx_attractions_destination_id', table_name='attractions')
    op.drop_index('idx_attractions_rating', table_name='attractions')
    op.drop_index('idx_attractions_search', table_name='attractions', postgresql_using='gin')
    op.drop_table('attractions')
    op.drop_index('idx_trip_item_order', table_name='trip_item')
    op.drop_index('idx_trip_item_trip_day_id', table_name='trip_item')
    op.drop_table('trip_item')
    op.drop_index('idx_ai_task_status', table_name='ai_task')
    op.drop_index('idx_ai_task_user_id', table_name='ai_task')
    op.drop_table('ai_task')
    op.drop_table('activity_types')
    op.drop_index('idx_favorite_user_id', table_name='favorite')
    op.drop_table('favorite')
    op.drop_index('idx_topic_place_order', table_name='topic_place')
    op.drop_index('idx_topic_place_topic_id', table_name='topic_place')
    op.drop_table('topic_place')
    op.drop_index('ix_location_is_favorite', table_name='location')
    op.drop_index('ix_location_is_highlight', table_name='location')
    op.drop_index('ix_location_location_name', table_name='location')
    op.drop_table('location')
    op.drop_index('idx_photo_related', table_name='photo')
    op.drop_index('idx_photo_user_id', table_name='photo')
    op.drop_table('photo')
    op.drop_index('idx_restaurants_cuisine_type', table_name='restaurants')
    op.drop_index('idx_restaurants_destination_id', table_name='restaurants')
    op.drop_index('idx_restaurants_rating', table_name='restaurants')
    op.drop_index('idx_restaurants_search', table_name='restaurants', postgresql_using='gin')
    op.drop_table('restaurants')
    op.drop_index('idx_topic_region', table_name='topic')
    op.drop_index('idx_topic_search', table_name='topic', postgresql_using='gin')
    op.drop_table('topic')
    op.drop_index('idx_footprint_date', table_name='footprint')
    op.drop_index('idx_footprint_user_id', table_name='footprint')
    op.drop_table('footprint')
    op.drop_index('idx_trip_created_at', table_name='trip')
    op.drop_index('idx_trip_user_id', table_name='trip')
    op.drop_table('trip')
    op.alter_column('destinations', 'country',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('destinations', 'city',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('destinations', 'region',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('destinations', 'latitude',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('destinations', 'longitude',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('destinations', 'highlights',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('destinations', 'best_time_to_visit',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('destinations', 'popularity_score',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('destinations', 'safety_score',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('destinations', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('destinations_name_country_key', 'destinations', type_='unique')
    op.drop_index('idx_destinations_country', table_name='destinations')
    op.drop_index('idx_destinations_name', table_name='destinations')
    op.drop_index('idx_destinations_popularity', table_name='destinations')
    op.drop_index('idx_destinations_search', table_name='destinations', postgresql_using='gin')
    op.create_index(op.f('ix_destinations_id'), 'destinations', ['id'], unique=False)
    op.create_index(op.f('ix_destinations_name'), 'destinations', ['name'], unique=False)
    op.create_foreign_key(None, 'travel_plan_ratings', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'travel_plans', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('favorite_locations', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('highlighted_locations', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('special_focus', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('photo_mood', sa.Text(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'photo_mood')
    op.drop_column('users', 'special_focus')
    op.drop_column('users', 'highlighted_locations')
    op.drop_column('users', 'favorite_locations')
    op.drop_constraint(None, 'travel_plans', type_='foreignkey')
    op.drop_constraint(None, 'travel_plan_ratings', type_='foreignkey')
    op.drop_index(op.f('ix_destinations_name'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_id'), table_name='destinations')
    op.create_index('idx_destinations_search', 'destinations', [sa.text("to_tsvector('chinese'::regconfig, (name::text || ' '::text) || description)")], unique=False, postgresql_using='gin')
    op.create_index('idx_destinations_popularity', 'destinations', ['popularity_score'], unique=False)
    op.create_index('idx_destinations_name', 'destinations', ['name'], unique=False)
    op.create_index('idx_destinations_country', 'destinations', ['country'], unique=False)
    op.create_unique_constraint('destinations_name_country_key', 'destinations', ['name', 'country'])
    op.alter_column('destinations', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('destinations', 'safety_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=True)
    op.alter_column('destinations', 'popularity_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=3, scale=1),
               nullable=True)
    op.alter_column('destinations', 'best_time_to_visit',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('destinations', 'highlights',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('destinations', 'longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=6),
               nullable=False)
    op.alter_column('destinations', 'latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=6),
               nullable=False)
    op.alter_column('destinations', 'region',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('destinations', 'city',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('destinations', 'country',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_table('trip',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('trip_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('days', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='trip_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='trip_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_trip_user_id', 'trip', ['user_id'], unique=False)
    op.create_index('idx_trip_created_at', 'trip', ['created_at'], unique=False)
    op.create_table('footprint',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('record_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('mood', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='footprint_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='footprint_pkey')
    )
    op.create_index('idx_footprint_user_id', 'footprint', ['user_id'], unique=False)
    op.create_index('idx_footprint_date', 'footprint', ['record_date'], unique=False)
    op.create_table('topic',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('topic_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('intro', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cover_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='topic_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_topic_search', 'topic', [sa.text("to_tsvector('chinese'::regconfig, (name::text || ' '::text) || intro)")], unique=False, postgresql_using='gin')
    op.create_index('idx_topic_region', 'topic', ['region'], unique=False)
    op.create_table('restaurants',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cuisine_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('opening_hours', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price_range', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('features', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contact_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('menu_highlights', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('images', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('destination_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name='restaurants_destination_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='restaurants_pkey'),
    sa.UniqueConstraint('name', 'destination_id', name='restaurants_name_destination_id_key')
    )
    op.create_index('idx_restaurants_search', 'restaurants', [sa.text("to_tsvector('chinese'::regconfig, (name::text || ' '::text) || description)")], unique=False, postgresql_using='gin')
    op.create_index('idx_restaurants_rating', 'restaurants', ['rating'], unique=False)
    op.create_index('idx_restaurants_destination_id', 'restaurants', ['destination_id'], unique=False)
    op.create_index('idx_restaurants_cuisine_type', 'restaurants', ['cuisine_type'], unique=False)
    op.create_table('photo',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('related_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('related_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='photo_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='photo_pkey')
    )
    op.create_index('idx_photo_user_id', 'photo', ['user_id'], unique=False)
    op.create_index('idx_photo_related', 'photo', ['related_type', 'related_id'], unique=False)
    op.create_table('location',
    sa.Column('location_id', sa.INTEGER(), autoincrement=True, nullable=False, comment='地点ID'),
    sa.Column('location_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='地点名称'),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='地址'),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True, comment='纬度'),
    sa.Column('longitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True, comment='经度'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='地点简介'),
    sa.Column('location_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='地点类型'),
    sa.Column('open_time', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='开放时间'),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='电话'),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='网址'),
    sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_highlight', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('added_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('media_images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('facilities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('location_id', name='location_pkey')
    )
    op.create_index('ix_location_location_name', 'location', ['location_name'], unique=False)
    op.create_index('ix_location_is_highlight', 'location', ['is_highlight'], unique=False)
    op.create_index('ix_location_is_favorite', 'location', ['is_favorite'], unique=False)
    op.create_table('topic_place',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('related_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('related_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_key_point', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('highlight_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name='topic_place_topic_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='topic_place_pkey')
    )
    op.create_index('idx_topic_place_topic_id', 'topic_place', ['topic_id'], unique=False)
    op.create_index('idx_topic_place_order', 'topic_place', ['topic_id', 'order_index'], unique=False)
    op.create_table('favorite',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('related_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('related_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorite_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='favorite_pkey'),
    sa.UniqueConstraint('user_id', 'related_type', 'related_id', name='favorite_user_id_related_type_related_id_key')
    )
    op.create_index('idx_favorite_user_id', 'favorite', ['user_id'], unique=False)
    op.create_table('activity_types',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('duration_range', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('age_restriction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='activity_types_pkey'),
    sa.UniqueConstraint('name', name='activity_types_name_key')
    )
    op.create_table('ai_task',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('input_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('output_trip_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('error_msg', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['output_trip_id'], ['trip.id'], name='ai_task_output_trip_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_task_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ai_task_pkey')
    )
    op.create_index('idx_ai_task_user_id', 'ai_task', ['user_id'], unique=False)
    op.create_index('idx_ai_task_status', 'ai_task', ['status'], unique=False)
    op.create_table('trip_item',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('trip_day_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('related_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('related_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('transport_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('transport_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trip_day_id'], ['trip_day.id'], name='trip_item_trip_day_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='trip_item_pkey')
    )
    op.create_index('idx_trip_item_trip_day_id', 'trip_item', ['trip_day_id'], unique=False)
    op.create_index('idx_trip_item_order', 'trip_item', ['trip_day_id', 'order_index'], unique=False)
    op.create_table('attractions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('opening_hours', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ticket_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('features', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accessibility', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contact_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('images', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('destination_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name='attractions_destination_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='attractions_pkey'),
    sa.UniqueConstraint('name', 'destination_id', name='attractions_name_destination_id_key')
    )
    op.create_index('idx_attractions_search', 'attractions', [sa.text("to_tsvector('chinese'::regconfig, (name::text || ' '::text) || description)")], unique=False, postgresql_using='gin')
    op.create_index('idx_attractions_rating', 'attractions', ['rating'], unique=False)
    op.create_index('idx_attractions_destination_id', 'attractions', ['destination_id'], unique=False)
    op.create_index('idx_attractions_category', 'attractions', ['category'], unique=False)
    op.create_table('checkin',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('related_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('related_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('mood', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='checkin_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='checkin_pkey')
    )
    op.create_index('idx_checkin_user_id', 'checkin', ['user_id'], unique=False)
    op.create_index('idx_checkin_created_at', 'checkin', ['created_at'], unique=False)
    op.create_table('trip_day',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('day_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name='trip_day_trip_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='trip_day_pkey'),
    sa.UniqueConstraint('trip_id', 'day_index', name='trip_day_trip_id_day_index_key')
    )
    op.create_index('idx_trip_day_trip_id', 'trip_day', ['trip_id'], unique=False)
    # ### end Alembic commands ###
